require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AdjectivesController do

  # This should return the minimal set of attributes required to create a valid
  # Adjective. As you add validations to Adjective, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AdjectivesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all adjectives as @adjectives" do
      adjective = Adjective.create! valid_attributes
      get :index, {}, valid_session
      assigns(:adjectives).should eq([adjective])
    end
  end

  describe "GET show" do
    it "assigns the requested adjective as @adjective" do
      adjective = Adjective.create! valid_attributes
      get :show, {:id => adjective.to_param}, valid_session
      assigns(:adjective).should eq(adjective)
    end
  end

  describe "GET new" do
    it "assigns a new adjective as @adjective" do
      get :new, {}, valid_session
      assigns(:adjective).should be_a_new(Adjective)
    end
  end

  describe "GET edit" do
    it "assigns the requested adjective as @adjective" do
      adjective = Adjective.create! valid_attributes
      get :edit, {:id => adjective.to_param}, valid_session
      assigns(:adjective).should eq(adjective)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Adjective" do
        expect {
          post :create, {:adjective => valid_attributes}, valid_session
        }.to change(Adjective, :count).by(1)
      end

      it "assigns a newly created adjective as @adjective" do
        post :create, {:adjective => valid_attributes}, valid_session
        assigns(:adjective).should be_a(Adjective)
        assigns(:adjective).should be_persisted
      end

      it "redirects to the created adjective" do
        post :create, {:adjective => valid_attributes}, valid_session
        response.should redirect_to(Adjective.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved adjective as @adjective" do
        # Trigger the behavior that occurs when invalid params are submitted
        Adjective.any_instance.stub(:save).and_return(false)
        post :create, {:adjective => { "name" => "invalid value" }}, valid_session
        assigns(:adjective).should be_a_new(Adjective)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Adjective.any_instance.stub(:save).and_return(false)
        post :create, {:adjective => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested adjective" do
        adjective = Adjective.create! valid_attributes
        # Assuming there are no other adjectives in the database, this
        # specifies that the Adjective created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Adjective.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => adjective.to_param, :adjective => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested adjective as @adjective" do
        adjective = Adjective.create! valid_attributes
        put :update, {:id => adjective.to_param, :adjective => valid_attributes}, valid_session
        assigns(:adjective).should eq(adjective)
      end

      it "redirects to the adjective" do
        adjective = Adjective.create! valid_attributes
        put :update, {:id => adjective.to_param, :adjective => valid_attributes}, valid_session
        response.should redirect_to(adjective)
      end
    end

    describe "with invalid params" do
      it "assigns the adjective as @adjective" do
        adjective = Adjective.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Adjective.any_instance.stub(:save).and_return(false)
        put :update, {:id => adjective.to_param, :adjective => { "name" => "invalid value" }}, valid_session
        assigns(:adjective).should eq(adjective)
      end

      it "re-renders the 'edit' template" do
        adjective = Adjective.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Adjective.any_instance.stub(:save).and_return(false)
        put :update, {:id => adjective.to_param, :adjective => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested adjective" do
      adjective = Adjective.create! valid_attributes
      expect {
        delete :destroy, {:id => adjective.to_param}, valid_session
      }.to change(Adjective, :count).by(-1)
    end

    it "redirects to the adjectives list" do
      adjective = Adjective.create! valid_attributes
      delete :destroy, {:id => adjective.to_param}, valid_session
      response.should redirect_to(adjectives_url)
    end
  end

end
