require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EnvolvementsController do

  # This should return the minimal set of attributes required to create a valid
  # Envolvement. As you add validations to Envolvement, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EnvolvementsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all envolvements as @envolvements" do
      envolvement = Envolvement.create! valid_attributes
      get :index, {}, valid_session
      assigns(:envolvements).should eq([envolvement])
    end
  end

  describe "GET show" do
    it "assigns the requested envolvement as @envolvement" do
      envolvement = Envolvement.create! valid_attributes
      get :show, {:id => envolvement.to_param}, valid_session
      assigns(:envolvement).should eq(envolvement)
    end
  end

  describe "GET new" do
    it "assigns a new envolvement as @envolvement" do
      get :new, {}, valid_session
      assigns(:envolvement).should be_a_new(Envolvement)
    end
  end

  describe "GET edit" do
    it "assigns the requested envolvement as @envolvement" do
      envolvement = Envolvement.create! valid_attributes
      get :edit, {:id => envolvement.to_param}, valid_session
      assigns(:envolvement).should eq(envolvement)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Envolvement" do
        expect {
          post :create, {:envolvement => valid_attributes}, valid_session
        }.to change(Envolvement, :count).by(1)
      end

      it "assigns a newly created envolvement as @envolvement" do
        post :create, {:envolvement => valid_attributes}, valid_session
        assigns(:envolvement).should be_a(Envolvement)
        assigns(:envolvement).should be_persisted
      end

      it "redirects to the created envolvement" do
        post :create, {:envolvement => valid_attributes}, valid_session
        response.should redirect_to(Envolvement.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved envolvement as @envolvement" do
        # Trigger the behavior that occurs when invalid params are submitted
        Envolvement.any_instance.stub(:save).and_return(false)
        post :create, {:envolvement => {  }}, valid_session
        assigns(:envolvement).should be_a_new(Envolvement)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Envolvement.any_instance.stub(:save).and_return(false)
        post :create, {:envolvement => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested envolvement" do
        envolvement = Envolvement.create! valid_attributes
        # Assuming there are no other envolvements in the database, this
        # specifies that the Envolvement created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Envolvement.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => envolvement.to_param, :envolvement => { "these" => "params" }}, valid_session
      end

      it "assigns the requested envolvement as @envolvement" do
        envolvement = Envolvement.create! valid_attributes
        put :update, {:id => envolvement.to_param, :envolvement => valid_attributes}, valid_session
        assigns(:envolvement).should eq(envolvement)
      end

      it "redirects to the envolvement" do
        envolvement = Envolvement.create! valid_attributes
        put :update, {:id => envolvement.to_param, :envolvement => valid_attributes}, valid_session
        response.should redirect_to(envolvement)
      end
    end

    describe "with invalid params" do
      it "assigns the envolvement as @envolvement" do
        envolvement = Envolvement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Envolvement.any_instance.stub(:save).and_return(false)
        put :update, {:id => envolvement.to_param, :envolvement => {  }}, valid_session
        assigns(:envolvement).should eq(envolvement)
      end

      it "re-renders the 'edit' template" do
        envolvement = Envolvement.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Envolvement.any_instance.stub(:save).and_return(false)
        put :update, {:id => envolvement.to_param, :envolvement => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested envolvement" do
      envolvement = Envolvement.create! valid_attributes
      expect {
        delete :destroy, {:id => envolvement.to_param}, valid_session
      }.to change(Envolvement, :count).by(-1)
    end

    it "redirects to the envolvements list" do
      envolvement = Envolvement.create! valid_attributes
      delete :destroy, {:id => envolvement.to_param}, valid_session
      response.should redirect_to(envolvements_url)
    end
  end

end
