require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FollowUpsController do

  # This should return the minimal set of attributes required to create a valid
  # FollowUp. As you add validations to FollowUp, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "notes" => "MyText" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FollowUpsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all follow_ups as @follow_ups" do
      follow_up = FollowUp.create! valid_attributes
      get :index, {}, valid_session
      assigns(:follow_ups).should eq([follow_up])
    end
  end

  describe "GET show" do
    it "assigns the requested follow_up as @follow_up" do
      follow_up = FollowUp.create! valid_attributes
      get :show, {:id => follow_up.to_param}, valid_session
      assigns(:follow_up).should eq(follow_up)
    end
  end

  describe "GET new" do
    it "assigns a new follow_up as @follow_up" do
      get :new, {}, valid_session
      assigns(:follow_up).should be_a_new(FollowUp)
    end
  end

  describe "GET edit" do
    it "assigns the requested follow_up as @follow_up" do
      follow_up = FollowUp.create! valid_attributes
      get :edit, {:id => follow_up.to_param}, valid_session
      assigns(:follow_up).should eq(follow_up)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FollowUp" do
        expect {
          post :create, {:follow_up => valid_attributes}, valid_session
        }.to change(FollowUp, :count).by(1)
      end

      it "assigns a newly created follow_up as @follow_up" do
        post :create, {:follow_up => valid_attributes}, valid_session
        assigns(:follow_up).should be_a(FollowUp)
        assigns(:follow_up).should be_persisted
      end

      it "redirects to the created follow_up" do
        post :create, {:follow_up => valid_attributes}, valid_session
        response.should redirect_to(FollowUp.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved follow_up as @follow_up" do
        # Trigger the behavior that occurs when invalid params are submitted
        FollowUp.any_instance.stub(:save).and_return(false)
        post :create, {:follow_up => { "notes" => "invalid value" }}, valid_session
        assigns(:follow_up).should be_a_new(FollowUp)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FollowUp.any_instance.stub(:save).and_return(false)
        post :create, {:follow_up => { "notes" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested follow_up" do
        follow_up = FollowUp.create! valid_attributes
        # Assuming there are no other follow_ups in the database, this
        # specifies that the FollowUp created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FollowUp.any_instance.should_receive(:update).with({ "notes" => "MyText" })
        put :update, {:id => follow_up.to_param, :follow_up => { "notes" => "MyText" }}, valid_session
      end

      it "assigns the requested follow_up as @follow_up" do
        follow_up = FollowUp.create! valid_attributes
        put :update, {:id => follow_up.to_param, :follow_up => valid_attributes}, valid_session
        assigns(:follow_up).should eq(follow_up)
      end

      it "redirects to the follow_up" do
        follow_up = FollowUp.create! valid_attributes
        put :update, {:id => follow_up.to_param, :follow_up => valid_attributes}, valid_session
        response.should redirect_to(follow_up)
      end
    end

    describe "with invalid params" do
      it "assigns the follow_up as @follow_up" do
        follow_up = FollowUp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FollowUp.any_instance.stub(:save).and_return(false)
        put :update, {:id => follow_up.to_param, :follow_up => { "notes" => "invalid value" }}, valid_session
        assigns(:follow_up).should eq(follow_up)
      end

      it "re-renders the 'edit' template" do
        follow_up = FollowUp.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FollowUp.any_instance.stub(:save).and_return(false)
        put :update, {:id => follow_up.to_param, :follow_up => { "notes" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested follow_up" do
      follow_up = FollowUp.create! valid_attributes
      expect {
        delete :destroy, {:id => follow_up.to_param}, valid_session
      }.to change(FollowUp, :count).by(-1)
    end

    it "redirects to the follow_ups list" do
      follow_up = FollowUp.create! valid_attributes
      delete :destroy, {:id => follow_up.to_param}, valid_session
      response.should redirect_to(follow_ups_url)
    end
  end

end
