require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InterjectionsController do

  # This should return the minimal set of attributes required to create a valid
  # Interjection. As you add validations to Interjection, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InterjectionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all interjections as @interjections" do
      interjection = Interjection.create! valid_attributes
      get :index, {}, valid_session
      assigns(:interjections).should eq([interjection])
    end
  end

  describe "GET show" do
    it "assigns the requested interjection as @interjection" do
      interjection = Interjection.create! valid_attributes
      get :show, {:id => interjection.to_param}, valid_session
      assigns(:interjection).should eq(interjection)
    end
  end

  describe "GET new" do
    it "assigns a new interjection as @interjection" do
      get :new, {}, valid_session
      assigns(:interjection).should be_a_new(Interjection)
    end
  end

  describe "GET edit" do
    it "assigns the requested interjection as @interjection" do
      interjection = Interjection.create! valid_attributes
      get :edit, {:id => interjection.to_param}, valid_session
      assigns(:interjection).should eq(interjection)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Interjection" do
        expect {
          post :create, {:interjection => valid_attributes}, valid_session
        }.to change(Interjection, :count).by(1)
      end

      it "assigns a newly created interjection as @interjection" do
        post :create, {:interjection => valid_attributes}, valid_session
        assigns(:interjection).should be_a(Interjection)
        assigns(:interjection).should be_persisted
      end

      it "redirects to the created interjection" do
        post :create, {:interjection => valid_attributes}, valid_session
        response.should redirect_to(Interjection.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved interjection as @interjection" do
        # Trigger the behavior that occurs when invalid params are submitted
        Interjection.any_instance.stub(:save).and_return(false)
        post :create, {:interjection => { "name" => "invalid value" }}, valid_session
        assigns(:interjection).should be_a_new(Interjection)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Interjection.any_instance.stub(:save).and_return(false)
        post :create, {:interjection => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested interjection" do
        interjection = Interjection.create! valid_attributes
        # Assuming there are no other interjections in the database, this
        # specifies that the Interjection created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Interjection.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => interjection.to_param, :interjection => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested interjection as @interjection" do
        interjection = Interjection.create! valid_attributes
        put :update, {:id => interjection.to_param, :interjection => valid_attributes}, valid_session
        assigns(:interjection).should eq(interjection)
      end

      it "redirects to the interjection" do
        interjection = Interjection.create! valid_attributes
        put :update, {:id => interjection.to_param, :interjection => valid_attributes}, valid_session
        response.should redirect_to(interjection)
      end
    end

    describe "with invalid params" do
      it "assigns the interjection as @interjection" do
        interjection = Interjection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Interjection.any_instance.stub(:save).and_return(false)
        put :update, {:id => interjection.to_param, :interjection => { "name" => "invalid value" }}, valid_session
        assigns(:interjection).should eq(interjection)
      end

      it "re-renders the 'edit' template" do
        interjection = Interjection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Interjection.any_instance.stub(:save).and_return(false)
        put :update, {:id => interjection.to_param, :interjection => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested interjection" do
      interjection = Interjection.create! valid_attributes
      expect {
        delete :destroy, {:id => interjection.to_param}, valid_session
      }.to change(Interjection, :count).by(-1)
    end

    it "redirects to the interjections list" do
      interjection = Interjection.create! valid_attributes
      delete :destroy, {:id => interjection.to_param}, valid_session
      response.should redirect_to(interjections_url)
    end
  end

end
