require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MeetingTimesController do

  # This should return the minimal set of attributes required to create a valid
  # MeetingTime. As you add validations to MeetingTime, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "time" => "2013-05-29 10:18:12" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MeetingTimesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all meeting_times as @meeting_times" do
      meeting_time = MeetingTime.create! valid_attributes
      get :index, {}, valid_session
      assigns(:meeting_times).should eq([meeting_time])
    end
  end

  describe "GET show" do
    it "assigns the requested meeting_time as @meeting_time" do
      meeting_time = MeetingTime.create! valid_attributes
      get :show, {:id => meeting_time.to_param}, valid_session
      assigns(:meeting_time).should eq(meeting_time)
    end
  end

  describe "GET new" do
    it "assigns a new meeting_time as @meeting_time" do
      get :new, {}, valid_session
      assigns(:meeting_time).should be_a_new(MeetingTime)
    end
  end

  describe "GET edit" do
    it "assigns the requested meeting_time as @meeting_time" do
      meeting_time = MeetingTime.create! valid_attributes
      get :edit, {:id => meeting_time.to_param}, valid_session
      assigns(:meeting_time).should eq(meeting_time)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MeetingTime" do
        expect {
          post :create, {:meeting_time => valid_attributes}, valid_session
        }.to change(MeetingTime, :count).by(1)
      end

      it "assigns a newly created meeting_time as @meeting_time" do
        post :create, {:meeting_time => valid_attributes}, valid_session
        assigns(:meeting_time).should be_a(MeetingTime)
        assigns(:meeting_time).should be_persisted
      end

      it "redirects to the created meeting_time" do
        post :create, {:meeting_time => valid_attributes}, valid_session
        response.should redirect_to(MeetingTime.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved meeting_time as @meeting_time" do
        # Trigger the behavior that occurs when invalid params are submitted
        MeetingTime.any_instance.stub(:save).and_return(false)
        post :create, {:meeting_time => { "time" => "invalid value" }}, valid_session
        assigns(:meeting_time).should be_a_new(MeetingTime)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MeetingTime.any_instance.stub(:save).and_return(false)
        post :create, {:meeting_time => { "time" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested meeting_time" do
        meeting_time = MeetingTime.create! valid_attributes
        # Assuming there are no other meeting_times in the database, this
        # specifies that the MeetingTime created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MeetingTime.any_instance.should_receive(:update).with({ "time" => "2013-05-29 10:18:12" })
        put :update, {:id => meeting_time.to_param, :meeting_time => { "time" => "2013-05-29 10:18:12" }}, valid_session
      end

      it "assigns the requested meeting_time as @meeting_time" do
        meeting_time = MeetingTime.create! valid_attributes
        put :update, {:id => meeting_time.to_param, :meeting_time => valid_attributes}, valid_session
        assigns(:meeting_time).should eq(meeting_time)
      end

      it "redirects to the meeting_time" do
        meeting_time = MeetingTime.create! valid_attributes
        put :update, {:id => meeting_time.to_param, :meeting_time => valid_attributes}, valid_session
        response.should redirect_to(meeting_time)
      end
    end

    describe "with invalid params" do
      it "assigns the meeting_time as @meeting_time" do
        meeting_time = MeetingTime.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MeetingTime.any_instance.stub(:save).and_return(false)
        put :update, {:id => meeting_time.to_param, :meeting_time => { "time" => "invalid value" }}, valid_session
        assigns(:meeting_time).should eq(meeting_time)
      end

      it "re-renders the 'edit' template" do
        meeting_time = MeetingTime.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MeetingTime.any_instance.stub(:save).and_return(false)
        put :update, {:id => meeting_time.to_param, :meeting_time => { "time" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested meeting_time" do
      meeting_time = MeetingTime.create! valid_attributes
      expect {
        delete :destroy, {:id => meeting_time.to_param}, valid_session
      }.to change(MeetingTime, :count).by(-1)
    end

    it "redirects to the meeting_times list" do
      meeting_time = MeetingTime.create! valid_attributes
      delete :destroy, {:id => meeting_time.to_param}, valid_session
      response.should redirect_to(meeting_times_url)
    end
  end

end
