require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SmartGroupRulesController do

  # This should return the minimal set of attributes required to create a valid
  # SmartGroupRule. As you add validations to SmartGroupRule, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SmartGroupRulesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all smart_group_rules as @smart_group_rules" do
      smart_group_rule = SmartGroupRule.create! valid_attributes
      get :index, {}, valid_session
      assigns(:smart_group_rules).should eq([smart_group_rule])
    end
  end

  describe "GET show" do
    it "assigns the requested smart_group_rule as @smart_group_rule" do
      smart_group_rule = SmartGroupRule.create! valid_attributes
      get :show, {:id => smart_group_rule.to_param}, valid_session
      assigns(:smart_group_rule).should eq(smart_group_rule)
    end
  end

  describe "GET new" do
    it "assigns a new smart_group_rule as @smart_group_rule" do
      get :new, {}, valid_session
      assigns(:smart_group_rule).should be_a_new(SmartGroupRule)
    end
  end

  describe "GET edit" do
    it "assigns the requested smart_group_rule as @smart_group_rule" do
      smart_group_rule = SmartGroupRule.create! valid_attributes
      get :edit, {:id => smart_group_rule.to_param}, valid_session
      assigns(:smart_group_rule).should eq(smart_group_rule)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SmartGroupRule" do
        expect {
          post :create, {:smart_group_rule => valid_attributes}, valid_session
        }.to change(SmartGroupRule, :count).by(1)
      end

      it "assigns a newly created smart_group_rule as @smart_group_rule" do
        post :create, {:smart_group_rule => valid_attributes}, valid_session
        assigns(:smart_group_rule).should be_a(SmartGroupRule)
        assigns(:smart_group_rule).should be_persisted
      end

      it "redirects to the created smart_group_rule" do
        post :create, {:smart_group_rule => valid_attributes}, valid_session
        response.should redirect_to(SmartGroupRule.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved smart_group_rule as @smart_group_rule" do
        # Trigger the behavior that occurs when invalid params are submitted
        SmartGroupRule.any_instance.stub(:save).and_return(false)
        post :create, {:smart_group_rule => {  }}, valid_session
        assigns(:smart_group_rule).should be_a_new(SmartGroupRule)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SmartGroupRule.any_instance.stub(:save).and_return(false)
        post :create, {:smart_group_rule => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested smart_group_rule" do
        smart_group_rule = SmartGroupRule.create! valid_attributes
        # Assuming there are no other smart_group_rules in the database, this
        # specifies that the SmartGroupRule created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SmartGroupRule.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => smart_group_rule.to_param, :smart_group_rule => { "these" => "params" }}, valid_session
      end

      it "assigns the requested smart_group_rule as @smart_group_rule" do
        smart_group_rule = SmartGroupRule.create! valid_attributes
        put :update, {:id => smart_group_rule.to_param, :smart_group_rule => valid_attributes}, valid_session
        assigns(:smart_group_rule).should eq(smart_group_rule)
      end

      it "redirects to the smart_group_rule" do
        smart_group_rule = SmartGroupRule.create! valid_attributes
        put :update, {:id => smart_group_rule.to_param, :smart_group_rule => valid_attributes}, valid_session
        response.should redirect_to(smart_group_rule)
      end
    end

    describe "with invalid params" do
      it "assigns the smart_group_rule as @smart_group_rule" do
        smart_group_rule = SmartGroupRule.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SmartGroupRule.any_instance.stub(:save).and_return(false)
        put :update, {:id => smart_group_rule.to_param, :smart_group_rule => {  }}, valid_session
        assigns(:smart_group_rule).should eq(smart_group_rule)
      end

      it "re-renders the 'edit' template" do
        smart_group_rule = SmartGroupRule.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SmartGroupRule.any_instance.stub(:save).and_return(false)
        put :update, {:id => smart_group_rule.to_param, :smart_group_rule => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested smart_group_rule" do
      smart_group_rule = SmartGroupRule.create! valid_attributes
      expect {
        delete :destroy, {:id => smart_group_rule.to_param}, valid_session
      }.to change(SmartGroupRule, :count).by(-1)
    end

    it "redirects to the smart_group_rules list" do
      smart_group_rule = SmartGroupRule.create! valid_attributes
      delete :destroy, {:id => smart_group_rule.to_param}, valid_session
      response.should redirect_to(smart_group_rules_url)
    end
  end

end
