require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TaggingsController do

  # This should return the minimal set of attributes required to create a valid
  # Tagging. As you add validations to Tagging, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TaggingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all taggings as @taggings" do
      tagging = Tagging.create! valid_attributes
      get :index, {}, valid_session
      assigns(:taggings).should eq([tagging])
    end
  end

  describe "GET show" do
    it "assigns the requested tagging as @tagging" do
      tagging = Tagging.create! valid_attributes
      get :show, {:id => tagging.to_param}, valid_session
      assigns(:tagging).should eq(tagging)
    end
  end

  describe "GET new" do
    it "assigns a new tagging as @tagging" do
      get :new, {}, valid_session
      assigns(:tagging).should be_a_new(Tagging)
    end
  end

  describe "GET edit" do
    it "assigns the requested tagging as @tagging" do
      tagging = Tagging.create! valid_attributes
      get :edit, {:id => tagging.to_param}, valid_session
      assigns(:tagging).should eq(tagging)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tagging" do
        expect {
          post :create, {:tagging => valid_attributes}, valid_session
        }.to change(Tagging, :count).by(1)
      end

      it "assigns a newly created tagging as @tagging" do
        post :create, {:tagging => valid_attributes}, valid_session
        assigns(:tagging).should be_a(Tagging)
        assigns(:tagging).should be_persisted
      end

      it "redirects to the created tagging" do
        post :create, {:tagging => valid_attributes}, valid_session
        response.should redirect_to(Tagging.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tagging as @tagging" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tagging.any_instance.stub(:save).and_return(false)
        post :create, {:tagging => {  }}, valid_session
        assigns(:tagging).should be_a_new(Tagging)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tagging.any_instance.stub(:save).and_return(false)
        post :create, {:tagging => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tagging" do
        tagging = Tagging.create! valid_attributes
        # Assuming there are no other taggings in the database, this
        # specifies that the Tagging created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tagging.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => tagging.to_param, :tagging => { "these" => "params" }}, valid_session
      end

      it "assigns the requested tagging as @tagging" do
        tagging = Tagging.create! valid_attributes
        put :update, {:id => tagging.to_param, :tagging => valid_attributes}, valid_session
        assigns(:tagging).should eq(tagging)
      end

      it "redirects to the tagging" do
        tagging = Tagging.create! valid_attributes
        put :update, {:id => tagging.to_param, :tagging => valid_attributes}, valid_session
        response.should redirect_to(tagging)
      end
    end

    describe "with invalid params" do
      it "assigns the tagging as @tagging" do
        tagging = Tagging.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tagging.any_instance.stub(:save).and_return(false)
        put :update, {:id => tagging.to_param, :tagging => {  }}, valid_session
        assigns(:tagging).should eq(tagging)
      end

      it "re-renders the 'edit' template" do
        tagging = Tagging.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tagging.any_instance.stub(:save).and_return(false)
        put :update, {:id => tagging.to_param, :tagging => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tagging" do
      tagging = Tagging.create! valid_attributes
      expect {
        delete :destroy, {:id => tagging.to_param}, valid_session
      }.to change(Tagging, :count).by(-1)
    end

    it "redirects to the taggings list" do
      tagging = Tagging.create! valid_attributes
      delete :destroy, {:id => tagging.to_param}, valid_session
      response.should redirect_to(taggings_url)
    end
  end

end
